

#define PIN_SPI_UWB_SCK GPIO_NUM_14
#define PIN_SPI_UWB_MISO GPIO_NUM_12
#define PIN_SPI_UWB_MOSI GPIO_NUM_13
#define PIN_SPI_UWB_CS GPIO_NUM_15


#define PIN_UWB_INTR GPIO_NUM_21
#define SPI_UWB_FREQ (20 * 1000000)
#define SPI_UWB_HOST SPI2_HOST

#define PIN_VBAT_SENSE_GND GPIO_NUM_32
#define PIN_VBAT_SENSE GPIO_NUM_34
#define PIN_BUTTON_SENSE GPIO_NUM_27

#define PIN_LED_R GPIO_NUM_4
#define PIN_LED_G GPIO_NUM_5
#define PIN_LED_B GPIO_NUM_18

#define CHANNEL_LED_R LEDC_CHANNEL_0
#define CHANNEL_LED_G LEDC_CHANNEL_1
#define CHANNEL_LED_B LEDC_CHANNEL_2

#define LED_SPEED_MODE LEDC_LOW_SPEED_MODE
#define LED_FREQUENCY 5000

#define TIMER_LED_R LEDC_TIMER_0
#define TIMER_LED_G LEDC_TIMER_1
#define TIMER_LED_B LEDC_TIMER_2